import { makeObjects } from '~/utils/helper';

export const en_auth_translations = {
  LOGIN: 'Login',
  REGISTERATION: 'Registeration',
  REGISTER: 'Register',
  USERNAME: 'Username',
  PASSWORD: 'Password',
  LOG_IN: 'Log In',
  VERIFY: 'Verify',
  FORGOT_PASSWORD: 'Forgot Password',
  NO_ACCOUNT: "Don't Have An Account ?",
  YES_ACCOUNT: 'Already Have An Account ?',
  PASSWORD_LABEL: 'Enter your password',
  USERNAME_LABEL: 'Enter your username',
  CONFIRM_PASSWORD: 'Confirm Password',
  GENDER: 'Gender',
  EMAIL: 'Email',
  BIRTH_DATE: 'Date of Birth',
  FIRST_NAME: 'First Name',
  LAST_NAME: 'Last Name',
  EMAIL_LABEL: 'Enter Your Email',
  CONFIRM_PASSWORD_LABEL: 'Enter Your Confirm Password',
  GENDER_LABEL: 'Enter Your Gender',
  BIRTH_DATE_LABEL: 'Pick Your Date of Birth',
  FIRST_NAME_LABEL: 'Enter Your First Name',
  LAST_NAME_LABEL: 'Enter Your Last Name',
  PHONE: 'Phone',
  PHONE_LABEL: 'Enter Your Phone',
  AGREE_TO_TERMS: 'I Agree To Terms & Conditions',
  RESEND: 'Resend',
  USE_PHONE: 'Send to Phone',
  USE_EMAIL: 'Send to Email',
  WAIT_FOR: 'Wait For',
  NO_CODE: "Didn't get the code ?",
  VERIFICATION_PLACEHOLDER: 'Enter Code Sent To Your {{sent_to}}',
  VERIFICATION: 'Verification',
  CANCEL: 'Cancel',
  NEXT: 'Next',
  PASS_REQUIRED: 'Password Required',
  USERNAME_REQUIRED: 'Email or Phone Required',
  PASS_LENGTH: 'Password must be atleast 5 characters',
  INVALID_EMAIL: 'Invalid Email',
  UNABLE_TO_LOGIN: 'Unable to login',
  LOGIN_SUCCESS: 'Successfully logged in',
  TRY_AGAIN: 'Please try again',
  EMAIL_OR_PHONE: 'Email or Phone',
  EMAIL_OR_PHONE_PLACEHOLDER: 'Enter your email or phone',
  INVALID_EMAIL_PHONE: 'Invalid email or phone',
  UNABLE_TO_SEND_VERIFICATION: 'Unable to send verification',
  UNABLE_TO_VERIFY: 'Unable to verify',
  CODE_SENT_TO: 'Code sent to {{sent_to}}',
  OTP_ERROR: 'Please fill out all slots',
  PASS_LEN_ERR: 'Password must be atleast 5 characters',
  PASS_NO_MATCH: 'Passwords dont match',
  REG_SUCCESS: 'Successfully registered',
  REG_ERR: 'Unable to register',
  AGREE_TO_TERMS_ERR: 'Agree to terms and conditions',
  INVALID_FIELDS: 'Invalid fields',
  INVALID_PHONE: 'Invalid phone',
  PASS_CHANGED_SUC: 'Password changed',
  PASS_CHANGE_ERR: 'Unable to change password',
};

type AuthStringsKeys = keyof typeof en_auth_translations;

// @ts-ignore
export const AUTH_STRINGS: { [placeholder in AuthStringsKeys]: string } = makeObjects(
  Object.keys(en_auth_translations)
);

export const am_auth_translations: { [placeholder in AuthStringsKeys]: string } = {
  LOGIN: 'ግባ',
  REGISTERATION: 'መመዝገብ',
  REGISTER: 'መመዝገብ',
  USERNAME: 'የተጠቃሚ ስም',
  PASSWORD: 'የይለፍ ቃል',
  LOG_IN: 'ግባ',
  VERIFY: 'አረጋግጥ',
  FORGOT_PASSWORD: 'የይለፍ ቃልዎን አረሳችው?',
  NO_ACCOUNT: 'መለያ የላቸውም?',
  YES_ACCOUNT: 'መለያ አላችው?',
  PASSWORD_LABEL: 'የይለፍ ቃልዎን ያስገቡ',
  USERNAME_LABEL: 'የተጠቃሚ ስምዎን ያስገቡ',
  CONFIRM_PASSWORD: 'የይለፍ ቃል ያረጋግጡ',
  GENDER: 'ፆታ',
  EMAIL: 'ኢሜይል',
  BIRTH_DATE: 'የትውልድ ቀን',
  FIRST_NAME: 'ስም',
  LAST_NAME: 'የቤተሰብ ስም',
  EMAIL_LABEL: 'ኢሜይልዎን ያስገቡ',
  CONFIRM_PASSWORD_LABEL: 'የይለፍ ቃልዎን ያረጋግጡ',
  GENDER_LABEL: 'ፆታዎን ያስገቡ',
  BIRTH_DATE_LABEL: 'የትውልድ ቀንዎን ይምረጡ',
  FIRST_NAME_LABEL: 'ስምዎን ያስገቡ',
  LAST_NAME_LABEL: 'የቤተሰብ ስምዎን ያስገቡ',
  PHONE: 'ስልክ',
  PHONE_LABEL: 'ስልክ ቁጥርዎን ያስገቡ',
  AGREE_TO_TERMS: 'ሁኔታዎችን እና ውሎችን እስማማለሁ',
  RESEND: 'እንደገና ላክ',
  USE_PHONE: 'ወደ ስልክ ላክ',
  USE_EMAIL: 'ወደ ኢሜይል ላክ',
  WAIT_FOR: 'ጠብቅ',
  NO_CODE: 'ኮዱን አላገኘኝም?',
  VERIFICATION_PLACEHOLDER: 'ወደ {{sent_to}} የተላከበትን ኮድ ያስገቡ',
  VERIFICATION: 'ማረጋገጫ',
  CANCEL: 'ሰርዝ',
  NEXT: 'ቀጣይ',
  PASS_REQUIRED: 'ፕስወርድ ያስፈልጋል',
  USERNAME_REQUIRED: 'ስልክ ወይምኢሜይል ያስፈልጋል',
  PASS_LENGTH: 'ፕስወርድ ቢያንስ 5 ቁምፊ መሆን አለበት',
  INVALID_EMAIL: 'ልክ ያልሆነ ኢሜል',
  UNABLE_TO_LOGIN: 'መግባት አልተቻለም',
  LOGIN_SUCCESS: 'በተሳካ ሁኔታ ገብተዋል',
  TRY_AGAIN: 'እባኮትን እንደገና ይሞክሩ',
  EMAIL_OR_PHONE: 'ኢሜል ወይም ስልክ',
  EMAIL_OR_PHONE_PLACEHOLDER: 'ኢሜልዎን ወይም ስልክዎን ያስገቡ',
  INVALID_EMAIL_PHONE: 'ልክ ያልሆነ ኢሜል ወይም ስልክ',
  UNABLE_TO_SEND_VERIFICATION: 'ማረጋገጫን ማላክ አልተቻለም',
  UNABLE_TO_VERIFY: 'ማረጋገጥ አልተቻለም',
  CODE_SENT_TO: 'ኮድ ወደ {{sent_to}} ተላከው',
  OTP_ERROR: 'እባክዎ ሁሉንም ክፍተቶች ይሙሉ',
  PASS_LEN_ERR: 'ፕስወርድ ቢያንስ 5 ቁምፊ መሆን አለበት',
  PASS_NO_MATCH: 'ፕስወርዶቹ አይዛመዱም',
  REG_SUCCESS: 'በተሳካ ሁኔታ ተመዝግበዋል',
  REG_ERR: 'መመዝገብ አልተቻለም',
  AGREE_TO_TERMS_ERR: 'ከመመሪያዎችና ከሁኔታዎች ጋር ይስማማሉ',
  INVALID_FIELDS: 'ልክ ያልሆኑ መስኮች',
  INVALID_PHONE: 'ልክ ያልሆነ ስልክ',
  PASS_CHANGED_SUC: 'ፕስወርድ ተቀይሯል',
  PASS_CHANGE_ERR: 'ፕስወርድ መቀየር አልተቻለም',
};
