export enum HOME_STRINGS {
  SELF_ASSESSMENT = 'Self Assessment',
  SELF_CARE_TECHNIQUES = 'Self Care Techniques',
  CANCEL = 'Cancel',
  DELETE = 'Delete',
  DELETED = 'Deleted',
  EDIT = 'Edit',
  SKIP = 'Skip',
  SAVE = 'Save',
  LOGOUT = 'Logout',
  LOGOUT_QNS = 'Are you sure you want to log out?',
  HOME = 'Home',
  REMINDER = 'Reminder',
  PROFILE = 'Profile',
  SETTING = 'Setting',
  FEEDBACK = 'Feedback',
  STATISTICS = 'Statistics',
  ABOUT_US = 'About Us',
  HELP = 'Help',
  CONTACT_US = 'Contact Us',
  YES = 'Yes',
  NO = 'No',
  CREATED_AT = 'Created At',
  EDITTED_AT = 'Editted At',
  NO_DESCRIPTION = 'No Description',
}
export const am_home_translations: { [placeholder in HOME_STRINGS]?: string } = {
  [HOME_STRINGS.SELF_ASSESSMENT]: 'ራስን መገምግም',
  [HOME_STRINGS.SELF_CARE_TECHNIQUES]: 'ራስን መጠበቂያ መንገዶች',
  [HOME_STRINGS.REMINDER]: 'ዕቅዶች እና ማስታወሻዎች',
  [HOME_STRINGS.CANCEL]: 'ሰርዝ',
  [HOME_STRINGS.DELETE]: 'ሰርዝ',
  [HOME_STRINGS.EDIT]: 'መለወጥ',
  [HOME_STRINGS.SKIP]: 'ዝለል',
  [HOME_STRINGS.SAVE]: 'አስቀምጥ',
  [HOME_STRINGS.NO]: 'አይ',
  [HOME_STRINGS.YES]: 'አዎ',
  [HOME_STRINGS.DELETED]: 'ተሰርዟል',
  [HOME_STRINGS.NO_DESCRIPTION]: 'መግለጫ የለም።',
};
